# Starter Pipeline
# .github/workflows/pipeline.yml

# 1) TRIGGER
on:
  workflow_dispatch:
  # push:
  #   branches: [ <branch> ]     # e.g. main
  #   paths:   [ "<path/**>" ]   # optional
  # pull_request:
  #   branches: [ <branch> ]

# 2) VARIABLES
env:
  Image_Name: "microservices"

# 3) JOBS
jobs:

  # 0) Install Docker (if needed)
  setup-docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker
        uses: docker/setup-docker-action@v4


  # 1) Login To ACR
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_REGISTRY }}
          username: ${{ secrets.ACR_ADMIN_USERNAME }}
          password: ${{ secrets.ACR_ADMIN_PASSWORD }}

  # 2) Get The Latest Git Hash to use as container tag
  get-tag:
    runs-on: ubuntu-latest
    needs: login
    outputs:
      tag: ${{ steps.get_tag.outputs.tag }}
    steps:
      - name: Get the latest git tag
        id: get_tag
        run: echo "::set-output name=tag::$(echo $GITHUB_SHA | cut -c1-7)"

  # 3) Build and Push Docker Image
  build-and-push:
    runs-on: self-hosted
    needs: login
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.ACR_REGISTRY }}/${{ env.Image_Name }}:${{ needs.get-tag.outputs.tag }}
          file: ./Dockerfile
