# Starter Pipeline
# .github/workflows/pipeline.yml

# 1) TRIGGER
on:
  workflow_dispatch:
  # push:
  #   branches: [ <branch> ]     # e.g. main
  #   paths:   [ "<path/**>" ]   # optional
  # pull_request:
  #   branches: [ <branch> ]

# 2) VARIABLES
env:
  Image_Name: "microservices"

# 3) JOBS
jobs:
  # 1) Build docker image and push to ACR
  Build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_REGISTRY }}
          username: ${{ secrets.ACR_ADMIN_USERNAME }}
          password: ${{ secrets.ACR_ADMIN_PASSWORD }}

      - name: Get hash commit
        run: |
          set -e
          docker_tag=$(echo $GITHUB_SHA | cut -c1-7)
          echo "IMAGE_TAG=$docker_tag"
          echo "IMAGE_TAG=$docker_tag" >> $GITHUB_ENV
          echo "IMAGE_NAME=${{ secrets.ACR_REGISTRY }}/${{ env.Image_Name }}:${{ env.IMAGE_TAG }}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.ACR_REGISTRY }}/${{ env.Image_Name }}:${{ env.IMAGE_TAG }}
          file: ./Dockerfile

  # 2) Deploy to Azure Kubernetes Service (AKS)
  Deploy:
    needs: Build
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Kubeconfig
        uses: Azure/k8s-set-context@v4
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Create Kubernetes secret for ACR
        uses: Azure/k8s-create-secret@v4
        with:
          container-registry-url: ${{ secrets.ACR_REGISTRY }}
          container-registry-username: ${{ secrets.ACR_ADMIN_USERNAME }}
          container-registry-password: ${{ secrets.ACR_ADMIN_PASSWORD }}
          secret-name: registry-pull-secret

      - name: Update image in Kubernetes deployment
        run: |
          set -e
          sed -i "s|image: .*|image: ${{ secrets.ACR_REGISTRY }}/${{ env.Image_Name }}:${{ env.IMAGE_TAG }}|g" $GITHUB_WORKSPACE/Deployment_k8s/Deployment.yaml

      - name: Print deployment manifest
        run: |
          set -e
          cd $GITHUB_WORKSPACE/Deployment_k8s

          # Print the combined deployment manifest
          echo "--- Combined Deployment Manifest ---"
          cat Deployment.yaml
          echo "------------------------------------"

      - name: Deploy to AKS
        uses: Azure/k8s-deploy@v4
        with:
          namespace: application-dev
          action: deploy
          manifests: |
              $GITHUB_WORKSPACE/Deployment_k8s/Deployment.yaml
          images: |
              ${{ secrets.ACR_REGISTRY }}/${{ env.Image_Name }}:${{ env.IMAGE_TAG }}
          imagepullsecrets: |
              registry-pull-secret