# Starter Pipeline
# .github/workflows/pipeline.yml

# 1) TRIGGER
on:
  workflow_dispatch:
  # push:
  #   branches: [ <branch> ]     # e.g. main
  #   paths:   [ "<path/**>" ]   # optional
  # pull_request:
  #   branches: [ <branch> ]

# 2) VARIABLES
env:
  Image_Name: "microservices"

# 3) JOBS
jobs:



  # 1) Login To ACR
  Build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_REGISTRY }}
          username: ${{ secrets.ACR_ADMIN_USERNAME }}
          password: ${{ secrets.ACR_ADMIN_PASSWORD }}

      - name: Get hash commit
        run: |
          set -e
          docker_tag=$(echo $GITHUB_SHA | cut -c1-7)
          echo "IMAGE_TAG=$docker_tag"
          echo "IMAGE_TAG=$docker_tag >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.ACR_REGISTRY }}/${{ env.Image_Name }}:${{ env.IMAGE_TAG }}
          file: ./Dockerfile



  # # 0) Install Docker (if needed)
  # setup-docker:
  #   runs-on: ubuntu-latest
  #   steps:
  #     -
  #       name: Set up Docker
  #       uses: docker/setup-docker-action@v4